# The west manifest file for Hypnos.
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#
# You can create your own manifest files and put them in any
# repository you want, to create your own custom Pinetime installation.
# For example, you could create a manifest file in your own
# out-of-tree application directory, which would pull the pinetime repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new pinetime installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: app

  remotes:
    - name: app
      url-base: https://github.com/zephyrproject-rtos

  # External projects
  #
  projects:
    - name: cmsis
      path: modules/hal/cmsis
      revision: c3bd2094f92d574377f7af2aec147ae181aa5f8e
    - name: hal_nordic
      path: modules/hal/nordic
      revision: 574493fe29c79140df4827ab5d4a23df79d03681
    - name: lvgl
      path: modules/lib/gui/lvgl
      revision: 31acbaa36e9e74ab88ac81e3d21e7f1d00a71136
    - name: littlefs
      path: modules/fs/littlefs
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c
    - name: mcuboot
      revision: 2fce9769b191411d580bbc65b043956c2ae9307e
      path: bootloader/mcuboot
    - name: mcumgr
      revision: 5c5055f5a7565f8152d75fcecf07262928b4d56e
      path: modules/lib/mcumgr
    - name: segger
      path: modules/debug/segger
      revision: 3a52ab222133193802d3c3b4d21730b9b1f1d2f6
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
    - name: tinycrypt
      path: modules/crypto/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: v2.6.1-rc2
  self:
    path: app
