/*
 * Copyright (c) 2020 Stephane Dorre
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_CTS816A_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_CTS816A_H_

#include <drivers/sensor.h>

enum cst816s_gesture {
    NONE,
    SLIDE_UP,
    SLIDE_DOWN,
    SLIDE_LEFT,
    SLIDE_RIGHT,
    CLICK,
    DOUBLE_CLICK,
    LONG_PRESS,
};

enum cst816s_channel {
	CST816S_CHAN_GESTURE = SENSOR_CHAN_PRIV_START,
	CST816S_CHAN_TOUCH_POINT_1,
    CST816S_CHAN_TOUCH_POINT_2,
};

/* If necessary at some point */
// enum cst816s_attribute {
// 	BMA421_ATTR_STEP_CNT_ENABLE = SENSOR_ATTR_PRIV_START,
// 	BMA421_ATTR_STEP_CNT_WATERMARK,
// 	BMA421_ATTR_STEP_CNT_RESET,
// 	BMA421_ATTR_STEP_CNT_PARAM,
// 	BMA421_ATTR_STEP_DTC_ENABLE,
// 	BMA421_ATTR_ANY_MOT_CONFIG,
// 	BMA421_ATTR_NO_MOT_CONFIG,
// 	BMA421_ATTR_VERSION_CONFIG,
// };

// enum cts816s_trigger {
// 	BMA421_TRIG_STEP_COUNT = SENSOR_TRIG_PRIV_START,
// 	BMA421_TRIG_STEP_DETECT,
// 	BMA421_TRIG_NO_MOTION,
// };

#endif /* ZEPHYR_INCLUDE_DRIVERS_SENSOR_CTS816A_H_ */